export const SET_BOUQUETS_FILTER = 'SET_BOUQUETS_FILTER'
export const SET_GIFTS_FILTER = 'SET_GIFTS_FILTER'
export const SET_PAYMENT_FILTER = 'SET_PAYMENT_FILTER'
export const SET_PROFILE_FILTER = 'SET_PROFILE_FILTER'
export const SET_BANK_CARDS_FILTER = 'SET_BANK_CARDS_FILTER'

export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const CHANGE_ITEM_QUANTITY = 'CHANGE_ITEM_QUANTITY'
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET'
export const CLEAR_BASKET = 'CLEAR_BASKET'

export const LOAD_BOUQUETS_REQUEST = 'LOAD_BOUQUETS_REQUEST'
export const LOAD_BOUQUETS_SUCCESS = 'LOAD_BOUQUETS_SUCCESS'
export const LOAD_BOUQUETS_FAILED = 'LOAD_BOUQUETS_FAILED'

export const LOAD_GIFTS_REQUEST = 'LOAD_GIFTS_REQUEST'
export const LOAD_GIFTS_SUCCESS = 'LOAD_GIFTS_SUCCESS'
export const LOAD_GIFTS_FAILED = 'LOAD_GIFTS_FAILED'

export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS'

export const LOAD_CITIES_REQUEST = 'LOAD_CITIES_REQUEST'
export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS'
export const LOAD_CITIES_FAILED = 'LOAD_CITIES_FAILED'

export const TOGGLE_CITIES = 'TOGGLE_CITIES'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const SET_CITY_REQUEST = 'SET_CITY_REQUEST'
export const SET_CITY_SUCCESS = 'SET_CITY_SUCCESS'

export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS'
export const TOKEN_IS_INVALID = 'TOKEN_IS_INVALID'
export const SET_CHECK_TOKEN = 'SET_CHECK_TOKEN'

export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEM_FAILED = 'GET_ITEM_FAILED'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_AUTH_FILTER = 'SET_AUTH_FILTER'

export const LOAD_ORDERS_REQUEST = 'LOAD_ORDERS_REQUEST'
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS'
export const LOAD_ORDERS_FAILED = 'LOAD_ORDERS_FAILED'

export const LOAD_SAVED_CARDS_REQUEST = 'LOAD_SAVED_CARDS_REQUEST'
export const LOAD_SAVED_CARDS_SUCCESS = 'LOAD_SAVED_CARDS_SUCCESS'
export const LOAD_SAVED_CARDS_ITEMS_SUCCESS = 'LOAD_SAVED_CARDS_ITEMS_SUCCESS'
export const LOAD_SAVED_CARDS_FAILED = 'LOAD_SAVED_CARDS_FAILED'

export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS'
export const ADD_CARD_FAILED = 'ADD_CARD_FAILED'
export const REMOVE_CARD = 'REMOVE_CARD'
export const CHANGE_CARD_STATUS = 'CHANGE_CARD_STATUS'
export const REMOVE_CHECK_CARD = 'REMOVE_CHECK_CARD'

export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'
export const CLEAR_AUTHORIZATION_ERROR = 'CLEAR_AUTHORIZATION_ERROR'

export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'

export const PAYMENT_FAILED = 'PAYMENT_FAILED'

export const ADD_ITEMS_TO_ORDER = 'ADD_ITEMS_TO_ORDER'
export const ADD_CHECKOUT_TO_ORDER = 'ADD_CHECKOUT_TO_ORDER'
export const ADD_POSTCARD_TO_ORDER = 'ADD_POSTCARD_TO_ORDER'
export const CLEAR_ORDER = 'CLEAR_ORDER'

export const TOGGLE_POPUP = 'TOGGLE_POPUP'
export const SHOW_ANIMATION = 'SHOW_ANIMATION'

export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLEAR_TOKEN_ERROR = 'CLEAR_TOKEN_ERROR'

export const SET_ACTIVE_TAG = 'SET_ACTIVE_TAG'
export const TOGGLE_TAGS = 'TOGGLE_TAGS'

export const VK_AUTH_URL = 'https://oauth.vk.com/authorize?client_id=6406813&display=popup&redirect_uri=https://vengoflowers.com/auth&response_type=code&v=5.73&state=vk'
export const FB_AUTH_URL = 'https://www.facebook.com/dialog/oauth?client_id=1484300015007993&redirect_uri=https://vengoflowers.com/auth&response_type=code&state=facebook'
export const MAP_URL = 'https://yandex.ru/map-widget/v1/?um=constructor%3Aaef544904743b0102d4f24c4ebf807b6910a9c1143a920a1b939a509cd943749&amp;source=constructor'




